name: Michael Geden
markdown: kramdown
highlighter: rouge
description: "Professional website and blog where I discuss statistics, visualization, computer science fundamentals, and occasionally bread."
url: "https://michaelgeden.com/"
# Google Analytics
google_analytics: UA-121201985-1
